import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import Card from "../components/card";
import styles from "../styles/Home.module.css";

import { fetchCoffeStores } from "../lib/coffe-stores";
import useTrackLocation from "../hooks/useTrackLocation";

export async function getStaticProps(staticProps) {
  const coffeStores = await fetchCoffeStores();

  return {
    props: {
      coffeStores,
    },
  };
}

export default function Home({ coffeStores }) {
  const { latLong, locationErrorMsg, handleTrackLocation, status } = useTrackLocation();

  console.log({ latLong, locationErrorMsg });

  const handleOnBannerBtnClick = (e) => {
    handleTrackLocation();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffe Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={status? "Locating...": "View stories nearby"}
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="Hero"
            width={700}
            height={400}
          />
        </div>
        {coffeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Portugal and 6 de Dic</h2>
            <div className={styles.cardLayout}>
              {coffeStores.map((item) => {
                return (
                  <Card
                    name={item.name}
                    href={`/coffee-store/${item.fsq_id}`}
                    imgUrl={item.imgUrl}
                    className={styles.card}
                    key={item.fsq_id}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
