import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import Card from "../components/card";
import styles from "../styles/Home.module.css";

import coffeStoresData from "../data/coffee-stores.json";
import { fetchCoffeStores } from "../lib/coffe-stores";

export async function getStaticProps(staticProps) {

  const data = await fetchCoffeStores();

  return {
    props: {
      coffeStores: data.results,
    },
  };
}



export default function Home({ coffeStores }) {
  const handleOnBannerBtnClick = (e) => {
    console.log("Hi banner button");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffe Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={"View stories nearby"}
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="Hero"
            width={700}
            height={400}
          />
        </div>
        {coffeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {coffeStores.map((item) => {
                return (
                  <Card
                    name={item.name}
                    href={`/coffee-store/${item.fsq_id}`}
                    imgUrl={item.categories[0].icon.prefix + item.categories[0].icon.suffix}
                    className={styles.card}
                    key={item.fsq_id}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
